# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='r',
        ),
        migrations.AddField(
            model_name='permission',
            name='r',
            field=models.ManyToManyField(to='permission_system.Role'),
        ),
    ]
