# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permission_system', '0002_auto_20180425_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='u_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='permission_system.User'),
        ),
    ]
