# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permission_system', '0003_role_u_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='u_id',
        ),
        migrations.AddField(
            model_name='user',
            name='r_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='permission_system.Role'),
        ),
    ]
