# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.Classroom'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='stu',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stu_info', to='student.Student'),
        ),
    ]
